const translations = {
    es: {
        "tr_title": "TRIVIAL",
        "tr_num_players": "Nº de Jugadores:",
        "tr_p1": "1 Jugador 👤",
        "tr_p2": "2 Jugadores 👥",
        "tr_p3": "3 Jugadores 👨‍👩‍👧",
        "tr_p4": "4 Jugadores 👨‍👩‍👧‍👦",
        "tr_start_btn": "▶️ INICIAR JUEGO",
        "tr_turn_of": "Turno de:",
        "tr_next_btn": "Siguiente >>",
        "tr_tut_btn": "❓ Instrucciones",
        "tr_tut_title": "📖 Cómo Jugar Trivial",
        "tr_tut_step1_t": "Selecciona Jugadores",
        "tr_tut_step1_d": "Elige de 1 a 4 jugadores e introduce sus nombres para empezar a competir.",
        "tr_tut_step2_t": "Responde Rápido",
        "tr_tut_step2_d": "Lee la pregunta y elige la respuesta correcta antes de que se acaben los 15 segundos.",
        "tr_tut_step3_t": "Gana Puntos",
        "tr_tut_step3_d": "Cada respuesta correcta te da 10 puntos. El jugador con más puntos al final gana.",
        "tr_player_name": "Nombre Jugador",
        "tr_player_default": "Jugador",
        "tr_points": "Puntos: ",
        "tr_tourney_end": "¡Torneo Finalizado!",
        "tr_winner_text": "Ganador: {name} con {pts} puntos.",
        "tr_great": "Genial",
        "tr_questions": [
          { texto: "¿Qué significa 'HTML'?", respuestas: [{ texto: "HyperText Markup Language", correct: true }, { texto: "High Tech Modern Language", correct: false }, { texto: "Hyperlink Text Mode List", correct: false }, { texto: "Hard To Make Logic", correct: false }] },
          { texto: "En CSS, ¿cómo centras un elemento flexiblemente?", respuestas: [{ texto: "float: center;", correct: false }, { texto: "display: flex; justify-content: center;", correct: true }, { texto: "margin: middle;", correct: false }, { texto: "text-align: middle;", correct: false }] },
          { texto: "¿Resultado de: console.log('2' + 2)?", respuestas: [{ texto: "4", correct: false }, { texto: "22", correct: true }, { texto: "NaN", correct: false }, { texto: "Error", correct: false }] },
          { texto: "¿Quién descifró el código Enigma?", respuestas: [{ texto: "Steve Jobs", correct: false }, { texto: "Bill Gates", correct: false }, { texto: "Alan Turing", correct: true }, { texto: "Ada Lovelace", correct: false }] },
          { texto: "Código HTTP para 'No Encontrado'", respuestas: [{ texto: "200", correct: false }, { texto: "404", correct: true }, { texto: "500", correct: false }, { texto: "403", correct: false }] }
        ]
    },
    en: {
        "tr_title": "TRIVIAL",
        "tr_num_players": "Number of Players:",
        "tr_p1": "1 Player 👤",
        "tr_p2": "2 Players 👥",
        "tr_p3": "3 Players 👨‍👩‍👧",
        "tr_p4": "4 Players 👨‍👩‍👧‍👦",
        "tr_start_btn": "▶️ START GAME",
        "tr_turn_of": "Turn of:",
        "tr_next_btn": "Next >>",
        "tr_tut_btn": "❓ Instructions",
        "tr_tut_title": "📖 How to Play Trivial",
        "tr_tut_step1_t": "Select Players",
        "tr_tut_step1_d": "Choose from 1 to 4 players and enter their names to start competing.",
        "tr_tut_step2_t": "Answer Fast",
        "tr_tut_step2_d": "Read the question and choose the correct answer before the 15 seconds run out.",
        "tr_tut_step3_t": "Earn Points",
        "tr_tut_step3_d": "Every correct answer gives you 10 points. The player with the most points wins.",
        "tr_player_name": "Player Name",
        "tr_player_default": "Player",
        "tr_points": "Points: ",
        "tr_tourney_end": "Tournament Finished!",
        "tr_winner_text": "Winner: {name} with {pts} points.",
        "tr_great": "Awesome",
        "tr_questions": [
          { texto: "What does 'HTML' stand for?", respuestas: [{ texto: "HyperText Markup Language", correct: true }, { texto: "High Tech Modern Language", correct: false }, { texto: "Hyperlink Text Mode List", correct: false }, { texto: "Hard To Make Logic", correct: false }] },
          { texto: "In CSS, how do you flex-center an element?", respuestas: [{ texto: "float: center;", correct: false }, { texto: "display: flex; justify-content: center;", correct: true }, { texto: "margin: middle;", correct: false }, { texto: "text-align: middle;", correct: false }] },
          { texto: "Result of: console.log('2' + 2)?", respuestas: [{ texto: "4", correct: false }, { texto: "22", correct: true }, { texto: "NaN", correct: false }, { texto: "Error", correct: false }] },
          { texto: "Who cracked the Enigma code?", respuestas: [{ texto: "Steve Jobs", correct: false }, { texto: "Bill Gates", correct: false }, { texto: "Alan Turing", correct: true }, { texto: "Ada Lovelace", correct: false }] },
          { texto: "HTTP code for 'Not Found'", respuestas: [{ texto: "200", correct: false }, { texto: "404", correct: true }, { texto: "500", correct: false }, { texto: "403", correct: false }] }
        ]
    }
};
