const translations = {
    es: {
        "tr_tut_btn": "❓ Instrucciones",
        "tr_title": "TRES EN RAYA",
        "tr_how_many": "¿Cuántos juegan?",
        "tr_1p": "1 Jugador (vs Robot 🤖)",
        "tr_2p": "2 Jugadores (Amigos 👫)",
        "tr_p1": "Jugador 1",
        "tr_p2": "Jugador 2 / Robot 🤖",
        "tr_play_btn": "▶️ ¡A JUGAR!",
        "tr_back_btn": "🏠 Volver al Inicio",
        "tr_cat": "😺 Gato",
        "tr_dog": "🐶 Perro",
        "tr_lion": "🦁 León",
        "tr_unicorn": "🦄 Unicornio",
        "tr_fox": "🦊 Zorro",
        "tr_bear": "🐻 Oso",
        "tr_dragon": "🐲 Dragón",
        "tr_oc": "🐙 Pulpo",
        "tr_tut_title": "📖 ¿Cómo Jugar?",
        "tr_tut_step1_t": "Elige tu equipo",
        "tr_tut_step1_d": "Selecciona si juegas solo contra el robot 🤖 o contra un amigo 👫.",
        "tr_tut_step2_t": "Escoge tu Emoji",
        "tr_tut_step2_d": "Cada jugador elige su animal favorito. ¡Será tu ficha en el tablero!",
        "tr_tut_step3_t": "Tres en línea",
        "tr_tut_step3_d": "Coloca tu emoji en los cuadros. ¡Gana quien consiga poner tres en raya antes!",
        "tr_tut_close": "¡ENTENDIDO! 🚀",
        "tr_loading": "Cargando...",
        "tr_again_btn": "🔄 Otra Vez",
        "tr_exit_btn": "🏠 Salir / Resultados",
        "tr_ranking": "🏆 Clasificación 🏆",
        "tr_loading_res": "Cargando resultados...",
        "tr_home_btn": "🏠 Menú Principal",
        "tr_clear_btn": "🗑️ Borrar Historial",
        "tr_tie": "¡Empate! 🤝",
        "tr_winner": "¡Ganador: {name} {avatar}! 🏆",
        "tr_player1": "Jugador 1",
        "tr_robot": "Robot 🤖",
        "tr_player2": "Jugador 2",
        "tr_play_again": "Jugar de nuevo",
        "tr_turn_of": "Turno de: {name} {avatar}",
        "tr_leave_title": "¿Salir al menú?",
        "tr_leave_yes": "Sí, salir",
        "tr_leave_no": "No, seguir",
        "tr_thinking": "Pensando... 🤖",
        "tr_tie_word": "Empate",
        "tr_no_games": "¡Aún no hay partidas jugadas!",
        "tr_last_game": "Última Partida",
        "tr_tie_excl": "¡Tablas!",
        "tr_victory": "¡Victoria!",
        "tr_recent_hist": "Historial Reciente:",
        "tr_match_num": "Partida #{num}"
    },
    en: {
        "tr_tut_btn": "❓ Instructions",
        "tr_title": "TIC-TAC-TOE",
        "tr_how_many": "How many players?",
        "tr_1p": "1 Player (vs Robot 🤖)",
        "tr_2p": "2 Players (Friends 👫)",
        "tr_p1": "Player 1",
        "tr_p2": "Player 2 / Robot 🤖",
        "tr_play_btn": "▶️ PLAY!",
        "tr_back_btn": "🏠 Back to Menu",
        "tr_cat": "😺 Cat",
        "tr_dog": "🐶 Dog",
        "tr_lion": "🦁 Lion",
        "tr_unicorn": "🦄 Unicorn",
        "tr_fox": "🦊 Fox",
        "tr_bear": "🐻 Bear",
        "tr_dragon": "🐲 Dragon",
        "tr_oc": "🐙 Octopus",
        "tr_tut_title": "📖 How to Play?",
        "tr_tut_step1_t": "Choose your team",
        "tr_tut_step1_d": "Select whether you play against a robot 🤖 or a friend 👫.",
        "tr_tut_step2_t": "Choose your Emoji",
        "tr_tut_step2_d": "Each player picks their favorite animal. It will be your piece on the board!",
        "tr_tut_step3_t": "Tic-Tac-Toe",
        "tr_tut_step3_d": "Place your emoji on the squares. The first to get three in a row wins!",
        "tr_tut_close": "GOT IT! 🚀",
        "tr_loading": "Loading...",
        "tr_again_btn": "🔄 Again",
        "tr_exit_btn": "🏠 Exit / Results",
        "tr_ranking": "🏆 Ranking 🏆",
        "tr_loading_res": "Loading results...",
        "tr_home_btn": "🏠 Main Menu",
        "tr_clear_btn": "🗑️ Clear History",
        "tr_tie": "Tie! 🤝",
        "tr_winner": "Winner: {name} {avatar}! 🏆",
        "tr_player1": "Player 1",
        "tr_robot": "Robot 🤖",
        "tr_player2": "Player 2",
        "tr_play_again": "Play again",
        "tr_turn_of": "Turn of: {name} {avatar}",
        "tr_leave_title": "Leave to menu?",
        "tr_leave_yes": "Yes, leave",
        "tr_leave_no": "No, stay",
        "tr_thinking": "Thinking... 🤖",
        "tr_tie_word": "Tie",
        "tr_no_games": "No games played yet!",
        "tr_last_game": "Last Game",
        "tr_tie_excl": "Draw!",
        "tr_victory": "Victory!",
        "tr_recent_hist": "Recent History:",
        "tr_match_num": "Match #{num}"
    }
};
