// utils/idiomas.js for Impostor
const TRANSLATIONS = {
  es: {
    title: "El Impostor",
    subtitle: "Juego de Detección",
    tutorialButton: "❓ ¿Cómo se juega?",
    difficultyLabel: "Dificultad",
    difficultyEasy: "🟢 Fácil",
    difficultyNormal: "🟡 Normal",
    difficultyHard: "🟠 Difícil",
    difficultyExtreme: "🔴 Extremo",
    categoryLabel: "Categoría",
    categoryFood: "🍕 Comida y Bebidas",
    categoryAnimals: "🐶 Animales",
    categoryEntertainment: "🎬 Cine y TV",
    categorySports: "⚽ Deportes",
    categoryGeography: "🌍 Geografía",
    categoryMusic: "🎵 Música",
    categoryProfessions: "💼 Profesiones",
    categoryTransport: "🚗 Transporte",
    categoryHistory: "🏛️ Historia",
    categoryScience: "🔬 Ciencia",
    relatedWordsLabel: "🎭 Modo Palabras Relacionadas",
    relatedWordsTooltip: "El impostor recibe una palabra relacionada en lugar de 'impostor'",
    numPlayersLabel: "Número de jugadores",
    numPlayersPlaceholder: "Mínimo 3 jugadores",
    numImpostorsLabel: "Número de impostores",
    numImpostorsPlaceholder: "Mínimo 1 impostor",
    playerNamesLabel: "Nombres de los jugadores",
    startButton: "Generar Palabra y Empezar",
    resetButton: "Empezar de 0",
    loadingMessage: "⚡ Generando palabra y tema...",
    infoText: "Se generará automáticamente una palabra aleatoria y un tema. Los impostores recibirán una palabra diferente.",
    warningMessage: "⚠️ Pasa el dispositivo al siguiente jugador. Asegúrate de que nadie más esté mirando.",
    themeLabel: "Tema",
    revealButton: "Ver mi palabra",
    yourWordLabel: "Tu palabra es:",
    nextPlayerButton: "Siguiente Jugador",
    playerLabel: "Jugador",
    nameLabel: "Nombre",
    minPlayersMessage: "Mínimo 3 jugadores",
    alertMinPlayers: "Necesitas al menos 3 jugadores",
    alertMinImpostors: "Necesitas al menos 1 impostor",
    alertImpostorsTooMany: "El número de impostores debe ser menor que el número de jugadores",
    alertEnterName: "Por favor ingresa el nombre del Jugador",
    tutorialTitle: "📖 Cómo Jugar",
    tutorialStep1Title: "Configura el Juego",
    tutorialStep1Text: "Selecciona la dificultad, categoría y número de jugadores e impostores.",
    tutorialStep2Title: "Ingresa los Nombres",
    tutorialStep2Text: "Escribe el nombre de cada jugador que participará.",
    tutorialStep3Title: "Genera y Revela",
    tutorialStep3Text: "Cada jugador verá su palabra en privado. Los impostores recibirán una palabra diferente.",
    tutorialStep4Title: "Discute y Descubre",
    tutorialStep4Text: "Hagan preguntas para descubrir quién es el impostor. ¡El impostor debe ocultarse!",
    tutorialCloseBtn: "¡Entendido!",
    language: "es",
  },
  en: {
    title: "The Impostor",
    subtitle: "Detection Game",
    tutorialButton: "❓ How to Play?",
    difficultyLabel: "Difficulty",
    difficultyEasy: "🟢 Easy",
    difficultyNormal: "🟡 Normal",
    difficultyHard: "🟠 Hard",
    difficultyExtreme: "🔴 Extreme",
    categoryLabel: "Category",
    categoryFood: "🍕 Food & Drinks",
    categoryAnimals: "🐶 Animals",
    categoryEntertainment: "🎬 Movies & TV",
    categorySports: "⚽ Sports",
    categoryGeography: "🌍 Countries & Cities",
    categoryMusic: "🎵 Music",
    categoryProfessions: "💼 Professions",
    categoryTransport: "🚗 Transport",
    categoryHistory: "🏛️ History",
    categoryScience: "🔬 Science",
    relatedWordsLabel: "🎭 Related Words Mode",
    relatedWordsTooltip: "Impostor receives a related word instead of 'impostor'",
    numPlayersLabel: "Number of players",
    numPlayersPlaceholder: "Minimum 3 players",
    numImpostorsLabel: "Number of impostors",
    numImpostorsPlaceholder: "Minimum 1 impostor",
    playerNamesLabel: "Player names",
    startButton: "Generate Word and Start",
    resetButton: "Start from Scratch",
    loadingMessage: "⚡ Generating word and theme...",
    infoText: "A random word and theme will be automatically generated. Impostors will receive a different word.",
    warningMessage: "⚠️ Pass the device to the next player. Make sure no one else is watching.",
    themeLabel: "Theme",
    revealButton: "See my word",
    yourWordLabel: "Your word is:",
    nextPlayerButton: "Next Player",
    playerLabel: "Player",
    nameLabel: "Name",
    minPlayersMessage: "Minimum 3 players",
    alertMinPlayers: "You need at least 3 players",
    alertMinImpostors: "You need at least 1 impostor",
    alertImpostorsTooMany: "The number of impostors must be less than the number of players",
    alertEnterName: "Please enter the name for Player",
    tutorialTitle: "📖 How to Play",
    tutorialStep1Title: "Configure the Game",
    tutorialStep1Text: "Select difficulty, category and number of players and impostors.",
    tutorialStep2Title: "Enter Names",
    tutorialStep2Text: "Write the name of each player who will participate.",
    tutorialStep3Title: "Generate and Reveal",
    tutorialStep3Text: "Each player will see their word privately. Impostors will receive a different word.",
    tutorialStep4Title: "Discuss and Discover",
    tutorialStep4Text: "Ask questions to discover who is the impostor. The impostor must hide!",
    tutorialCloseBtn: "Got it!",
    language: "en",
  }
};
