const translations = {
    es: {
        "me_k_title": "MEMORY KIDS",
        "me_k_players": "👥 Jugadores:",
        "me_k_1p": "1 Jugador 👤",
        "me_k_2p": "2 Jugadores 👥",
        "me_k_3p": "3 Jugadores 👨‍👩‍👧",
        "me_k_4p": "4 Jugadores 👨‍👩‍👧‍👦",
        "me_k_play_btn": "▶️ ¡A JUGAR!",
        "me_k_back_btn": "🏠 Volver al Inicio",
        "me_k_tut_btn": "❓ Instrucciones",
        "me_k_tut_title": "📖 ¿Cómo Jugar?",
        "me_k_tut_step1_t": "¡Elige a tus amigos!",
        "me_k_tut_step1_d": "Selecciona cuántos amigos vais a jugar y escribe vuestros nombres.",
        "me_k_tut_step2_t": "Busca la pareja",
        "me_k_tut_step2_d": "Pulsa una carta para ver qué animal tiene. ¡Luego busca su pareja igual!",
        "me_k_tut_step3_t": "Sigue jugando",
        "me_k_tut_step3_d": "Si encuentras una pareja, ¡vuelves a jugar! Si fallas, le toca al siguiente amigo.",
        "me_k_tut_step4_t": "¡Gana el mejor!",
        "me_k_tut_step4_d": "Quien encuentre más parejas al final del juego será el ganador ⭐.",
        "me_k_tut_close": "¡ENTENDIDO! 🚀",
        "me_k_player_def": "Jugador",
        "me_k_pts": "pts",
        "me_k_game_over": "¡Juego Terminado!",
        "me_k_tie": "¡Empate! Todos sois unos cracks 🦄",
        "me_k_winner": "¡Ha ganado <b>{name}</b> con {pts} puntos! 🏆",
        "me_k_play_again": "Jugar otra vez"
    },
    en: {
        "me_k_title": "MEMORY KIDS",
        "me_k_players": "👥 Players:",
        "me_k_1p": "1 Player 👤",
        "me_k_2p": "2 Players 👥",
        "me_k_3p": "3 Players 👨‍👩‍👧",
        "me_k_4p": "4 Players 👨‍👩‍👧‍👦",
        "me_k_play_btn": "▶️ PLAY!",
        "me_k_back_btn": "🏠 Back to Menu",
        "me_k_tut_btn": "❓ Instructions",
        "me_k_tut_title": "📖 How to Play?",
        "me_k_tut_step1_t": "Choose your friends!",
        "me_k_tut_step1_d": "Select how many friends will play and write down your names.",
        "me_k_tut_step2_t": "Find the match",
        "me_k_tut_step2_d": "Tap a card to see what animal it has. Then find its exact pair!",
        "me_k_tut_step3_t": "Keep playing",
        "me_k_tut_step3_d": "If you find a pair, you play again! If you fail, it's the next friend's turn.",
        "me_k_tut_step4_t": "The best wins!",
        "me_k_tut_step4_d": "Whoever finds the most pairs by the end wins ⭐.",
        "me_k_tut_close": "GOT IT! 🚀",
        "me_k_player_def": "Player",
        "me_k_pts": "pts",
        "me_k_game_over": "Game Over!",
        "me_k_tie": "Tie! You are all awesome 🦄",
        "me_k_winner": "<b>{name}</b> won with {pts} points! 🏆",
        "me_k_play_again": "Play again"
    }
};
