const translations = {
    es: {
        "cn_title": "CUENTA NÚMEROS",
        "cn_how_many": "¿Cuántos jugadores?",
        "cn_play_btn": "▶️ ¡A JUGAR!",
        "cn_choose_chal": "Elige tu Reto",
        "cn_count_chal": "Contar",
        "cn_sum_chal": "Sumar",
        "cn_sub_chal": "Restar",
        "cn_back_home": "🏠 Volver al Inicio",
        "cn_delete": "BORRAR",
        "cn_exit": "🏠 Salir",
        "cn_winners": "🏆 GANADORES 🏆",
        "cn_main_menu": "🏠 MENÚ PRINCIPAL",
        "cn_tut_btn": "❓ Instrucciones",
        "cn_tut_title": "📖 ¿Cómo Jugar?",
        "cn_tut_step1_t": "¡Elige tu reto!",
        "cn_tut_step1_d": "Puedes elegir entre contar frutas ricas 🍎, sumar números ➕ o restar ➖.",
        "cn_tut_step2_t": "Escribe la respuesta",
        "cn_tut_step2_d": "Mira bien la pantalla y escribe la respuesta usando los botones de números.",
        "cn_tut_step3_t": "¡Comprueba!",
        "cn_tut_step3_d": "Cuando tengas el número, pulsa el botón verde ✅ para ver si has acertado.",
        "cn_tut_step4_t": "Gana Estrellas",
        "cn_tut_step4_d": "Cada acierto te da estrellas ⭐. ¡Consigue todas las que puedas!",
        "cn_player_def": "Jugador",
        "cn_ready": "¿Listos?",
        "cn_lets_go": "¡Vamos!",
        "cn_good": "¡Bien {name}! 🎉",
        "cn_points": "+10 Puntos",
        "cn_oh_no": "¡Oh no! 😅",
        "cn_it_was": "Era {ans}",
        "cn_almost": "¡Casi!",
        "cn_minus_pts": "(-2 pts)",
        "cn_turn_end": "Fin de turno: {name}",
        "cn_next_turn": "<h3>👉 ¡Le toca a {name}!</h3>",
        "cn_im_ready": "¡Estoy listo!",
        "cn_leave": "¿Salir?",
        "cn_lose_prog": "Se perderá el progreso"
    },
    en: {
        "cn_title": "COUNT NUMBERS",
        "cn_how_many": "How many players?",
        "cn_play_btn": "▶️ PLAY!",
        "cn_choose_chal": "Choose your Challenge",
        "cn_count_chal": "Count",
        "cn_sum_chal": "Sum",
        "cn_sub_chal": "Subtract",
        "cn_back_home": "🏠 Back to Home",
        "cn_delete": "DELETE",
        "cn_exit": "🏠 Exit",
        "cn_winners": "🏆 WINNERS 🏆",
        "cn_main_menu": "🏠 MAIN MENU",
        "cn_tut_btn": "❓ Instructions",
        "cn_tut_title": "📖 How to Play?",
        "cn_tut_step1_t": "Choose your challenge!",
        "cn_tut_step1_d": "You can choose between counting tasty fruits 🍎, adding numbers ➕ or subtracting ➖.",
        "cn_tut_step2_t": "Write the answer",
        "cn_tut_step2_d": "Look closely at the screen and write the answer using the number buttons.",
        "cn_tut_step3_t": "Check it!",
        "cn_tut_step3_d": "When you have the number, press the green button ✅ to see if you are right.",
        "cn_tut_step4_t": "Earn Stars",
        "cn_tut_step4_d": "Every correct answer gives you stars ⭐. Get as many as you can!",
        "cn_player_def": "Player",
        "cn_ready": "Ready?",
        "cn_lets_go": "Let's go!",
        "cn_good": "Great {name}! 🎉",
        "cn_points": "+10 Points",
        "cn_oh_no": "Oh no! 😅",
        "cn_it_was": "It was {ans}",
        "cn_almost": "Almost!",
        "cn_minus_pts": "(-2 pts)",
        "cn_turn_end": "End of turn: {name}",
        "cn_next_turn": "<h3>👉 It's {name}'s turn!</h3>",
        "cn_im_ready": "I'm ready!",
        "cn_leave": "Exit?",
        "cn_lose_prog": "Progress will be lost"
    }
};
