const translations = {
    es: {
        "cl_title": "CUENTA LETRAS",
        "cl_mode_solo": "👤 Solo",
        "cl_mode_coop": "👥 Cooperativo",
        "cl_q_players": "¿Cuántos jugadores?",
        "cl_p2": "2 Jugadores 👥",
        "cl_p3": "3 Jugadores 👨‍👩‍👧",
        "cl_p4": "4 Jugadores 👨‍👩‍👧‍👦",
        "cl_play_btn": "▶️ ¡A JUGAR!",
        "cl_exit_menu": "🏠 Salir al Menú",
        "cl_choose_mode": "Elige modo para esta ronda",
        "cl_mode_img": "🖼️ Visual",
        "cl_mode_series": "🔢 Series",
        "cl_mode_letters": "🔤 Letras",
        "cl_mode_en": "🇬🇧 Inglés",
        "cl_winners": "🏆 GANADORES 🏆",
        "cl_main_menu": "🏠 MENÚ PRINCIPAL",
        "cl_tut_btn": "❓ Instrucciones",
        "cl_p1_plc": "Nombre Jugador 1",
        "cl_p1_val": "Jugador 1",
        "cl_tut_title": "📖 ¿Cómo Jugar?",
        "cl_tut_step1_t": "Elige tu modo",
        "cl_tut_step1_d": "Puedes jugar solo o con amigos. ¡Tú decides quién es el más rápido!",
        "cl_tut_step2_t": "Selecciona Categoría",
        "cl_tut_step2_d": "Elige entre Imágenes, Series, Letras o Inglés para empezar tu ronda.",
        "cl_tut_step3_t": "Completa el hueco",
        "cl_tut_step3_d": "Mira la pista y elige la letra o el número que falta para ganar puntos.",
        "cl_tut_step4_t": "¡Acierta pronto!",
        "cl_tut_step4_d": "Si fallas, la pregunta valdrá menos puntos. ¡Acierta a la primera para el 10!",
        "cl_no_name_title": "¡Falta nombre!",
        "cl_no_name_text": "Por favor, escribe quién va a jugar.",
        "cl_player_def": "Jugador",
        "cl_next_turn_title": "¡Siguiente turno!",
        "cl_next_turn_text": "Le toca a: {name}",
        "cl_leave_title": "¿Salir al menú?",
        "cl_leave_text": "Se perderá el progreso actual.",
        "cl_yes_leave": "SÍ, SALIR",
        "cl_cancel": "CANCELAR"
    },
    en: {
        "cl_title": "COUNT LETTERS",
        "cl_mode_solo": "👤 Solo",
        "cl_mode_coop": "👥 Co-op",
        "cl_q_players": "How many players?",
        "cl_p2": "2 Players 👥",
        "cl_p3": "3 Players 👨‍👩‍👧",
        "cl_p4": "4 Players 👨‍👩‍👧‍👦",
        "cl_play_btn": "▶️ PLAY!",
        "cl_exit_menu": "🏠 Exit to Menu",
        "cl_choose_mode": "Choose mode for this round",
        "cl_mode_img": "🖼️ Visual",
        "cl_mode_series": "🔢 Series",
        "cl_mode_letters": "🔤 Letters",
        "cl_mode_en": "🇬🇧 English",
        "cl_winners": "🏆 WINNERS 🏆",
        "cl_main_menu": "🏠 MAIN MENU",
        "cl_tut_btn": "❓ Instructions",
        "cl_p1_plc": "Player 1 Name",
        "cl_p1_val": "Player 1",
        "cl_tut_title": "📖 How to Play?",
        "cl_tut_step1_t": "Choose your mode",
        "cl_tut_step1_d": "You can play solo or with friends. You decide who is the fastest!",
        "cl_tut_step2_t": "Select Category",
        "cl_tut_step2_d": "Choose between Images, Series, Letters or English to start your round.",
        "cl_tut_step3_t": "Fill the gap",
        "cl_tut_step3_d": "Look at the clue and choose the missing letter or number to earn points.",
        "cl_tut_step4_t": "Answer fast!",
        "cl_tut_step4_d": "If you fail, the question will be worth less points. Answer right the first time for 10!",
        "cl_no_name_title": "Missing name!",
        "cl_no_name_text": "Please write down who is going to play.",
        "cl_player_def": "Player",
        "cl_next_turn_title": "Next turn!",
        "cl_next_turn_text": "It's {name}'s turn",
        "cl_leave_title": "Exit to menu?",
        "cl_leave_text": "Current progress will be lost.",
        "cl_yes_leave": "YES, EXIT",
        "cl_cancel": "CANCEL"
    }
};
