const translations = {
    es: {
        "bj_title": "BLACKJACK",
        "bj_player_name": "Nombre del Jugador:",
        "bj_placeholder_name": "Tu nombre...",
        "bj_start_btn": "▶️ INICIAR JUEGO",
        "bj_bank": "BANCA",
        "bj_hit_btn": "Pedir Carta",
        "bj_stand_btn": "Plantarse",
        "bj_restart_btn": "Nueva Partida",
        "bj_tut_btn": "❓ Instrucciones",
        "bj_tut_title": "📖 Cómo Jugar Blackjack",
        "bj_tut_step1_t": "Objetivo del Juego",
        "bj_tut_step1_d": "Suma 21 puntos o acércate lo máximo posible sin pasarte. ¡Si te pasas, pierdes!",
        "bj_tut_step2_t": "Valor de las Cartas",
        "bj_tut_step2_d": "Las figuras valen 10. Las cartas numéricas valen su número.",
        "bj_tut_step3_t": "Tu Turno",
        "bj_tut_step3_d": "Puedes \"Pedir Carta\" para acercarte a 21, o \"Plantarte\" si crees que tu puntuación es buena.",
        "bj_tut_step4_t": "La Banca",
        "bj_tut_step4_d": "La banca jugará primero. Luego jugarás tú, ¡intenta superar su puntuación!",
        "bj_tut_close": "¡ENTENDIDO! 🚀",
        "bj_player_label": "Jugador: ",
        "bj_player_default": "Jugador",
        "bj_bank_playing": "La banca está jugando...",
        "bj_your_turn": "¡Tu turno! Pide carta o plántate",
        "bj_win_banca_bust": "¡GANASTE! La banca se pasó de 21",
        "bj_lose_bust": "PERDISTE! Te pasaste de 21",
        "bj_tie_21": "EMPATE! Ambos tienen 21 puntos",
        "bj_lose_bust_pts": "PERDISTE! Te pasaste con {pts} puntos",
        "bj_win_banca_bust_pts": "GANASTE! La banca se pasó con {pts} puntos",
        "bj_win_pts": "GANASTE! {p} vs {b}",
        "bj_lose_pts": "PERDISTE! {p} vs {b}",
        "bj_tie_pts": "EMPATE! Ambos con {pts} puntos"
    },
    en: {
        "bj_title": "BLACKJACK",
        "bj_player_name": "Player Name:",
        "bj_placeholder_name": "Your name...",
        "bj_start_btn": "▶️ START GAME",
        "bj_bank": "BANK",
        "bj_hit_btn": "Hit",
        "bj_stand_btn": "Stand",
        "bj_restart_btn": "New Game",
        "bj_tut_btn": "❓ Instructions",
        "bj_tut_title": "📖 How to Play Blackjack",
        "bj_tut_step1_t": "Game Objective",
        "bj_tut_step1_d": "Score 21 points or get as close as possible without busting. If you bust, you lose!",
        "bj_tut_step2_t": "Card Values",
        "bj_tut_step2_d": "Face cards are worth 10. Number cards are worth their number.",
        "bj_tut_step3_t": "Your Turn",
        "bj_tut_step3_d": "You can \"Hit\" to get closer to 21, or \"Stand\" if you think your score is good.",
        "bj_tut_step4_t": "The Bank",
        "bj_tut_step4_d": "The bank plays first. Then you play, try to beat its score!",
        "bj_tut_close": "GOT IT! 🚀",
        "bj_player_label": "Player: ",
        "bj_player_default": "Player",
        "bj_bank_playing": "The bank is playing...",
        "bj_your_turn": "Your turn! Hit or stand",
        "bj_win_banca_bust": "YOU WIN! The bank busted",
        "bj_lose_bust": "YOU LOSE! You busted",
        "bj_tie_21": "TIE! Both have 21 points",
        "bj_lose_bust_pts": "YOU LOSE! You busted with {pts} points",
        "bj_win_banca_bust_pts": "YOU WIN! The bank busted with {pts} points",
        "bj_win_pts": "YOU WIN! {p} vs {b}",
        "bj_lose_pts": "YOU LOSE! {p} vs {b}",
        "bj_tie_pts": "TIE! Both with {pts} points"
    }
};
