const translations = {
    es: {
        "ta_title": "TABÚ",
        "ta_team_name": "Nombre del Equipo:",
        "ta_team_placeholder": "Nombre del equipo...",
        "ta_min_teams": "👥 MÍNIMO 2 EQUIPOS",
        "ta_play_btn": "¡A JUGAR!",
        "ta_multiplayer": "Edición Multijugador",
        "ta_turn_of": "TURNO DE:",
        "ta_team_1": "EQUIPO 1",
        "ta_total_score": "Puntuación total:",
        "ta_pass_phone": "Pásale el móvil al equipo...",
        "ta_start_time": "🚀 EMPEZAR TIEMPO",
        "ta_playing_q": "Jugando: ???",
        "ta_playing": "Jugando: ",
        "ta_loading": "CARGANDO...",
        "ta_correct": "✅ ACERTADA",
        "ta_pass": "❌ TABÚ / PASO",
        "ta_round_points": "Puntos ronda: ",
        "ta_ranking": "🏆 CLASIFICACIÓN",
        "ta_new_game": "🔄 Nueva Partida",
        "ta_tut_btn": "❓ Instrucciones",
        "ta_tut_title": "📖 Cómo Jugar Tabú",
        "ta_tut_step1_t": "Organiza los Equipos",
        "ta_tut_step1_d": "Añade los nombres de los equipos que van a competir. Se necesitan al menos 2 equipos.",
        "ta_tut_step2_t": "Describe la Palabra",
        "ta_tut_step2_d": "Un miembro del equipo debe describir la palabra principal (azul) sin usar las palabras prohibidas (rojas).",
        "ta_tut_step3_t": "¡Nada de Trampas!",
        "ta_tut_step3_d": "Si dices una palabra prohibida o haces gestos no permitidos, el equipo contrario debe pulsar TABÚ.",
        "ta_tut_step4_t": "Gana el Mejor",
        "ta_tut_step4_d": "Cada acierto suma 1 punto. El equipo con más aciertos al final de todas las rondas será el ganador.",
        "ta_tut_close": "¡ENTENDIDO! 🚀"
    },
    en: {
        "ta_title": "TABOO",
        "ta_team_name": "Team Name:",
        "ta_team_placeholder": "Team name...",
        "ta_min_teams": "👥 MIN 2 TEAMS",
        "ta_play_btn": "PLAY!",
        "ta_multiplayer": "Multiplayer Edition",
        "ta_turn_of": "TURN FOR:",
        "ta_team_1": "TEAM 1",
        "ta_total_score": "Total score:",
        "ta_pass_phone": "Pass the phone to the team...",
        "ta_start_time": "🚀 START TIMER",
        "ta_playing_q": "Playing: ???",
        "ta_playing": "Playing: ",
        "ta_loading": "LOADING...",
        "ta_correct": "✅ CORRECT",
        "ta_pass": "❌ TABOO / PASS",
        "ta_round_points": "Round points: ",
        "ta_ranking": "🏆 RANKING",
        "ta_new_game": "🔄 New Game",
        "ta_tut_btn": "❓ Instructions",
        "ta_tut_title": "📖 How to Play Taboo",
        "ta_tut_step1_t": "Organize Teams",
        "ta_tut_step1_d": "Add the names of competing teams. At least 2 teams are required.",
        "ta_tut_step2_t": "Describe the Word",
        "ta_tut_step2_d": "One team member must describe the main word (blue) without using the forbidden words (red).",
        "ta_tut_step3_t": "No Cheating!",
        "ta_tut_step3_d": "If you say a forbidden word or make illegal gestures, the opposing team must press TABOO.",
        "ta_tut_step4_t": "The Best Wins",
        "ta_tut_step4_d": "Every correct answer adds 1 point. The team with the most correct answers at the end wins.",
        "ta_tut_close": "GOT IT! 🚀"
    }
};
