const translations = {
    es: {
        "ta_k_title": "TABÚ KIDS",
        "ta_k_add_players": "Añade a los jugadores:",
        "ta_k_name_plc": "Nombre...",
        "ta_k_min_players": "MÍNIMO 2 JUGADORES",
        "ta_k_play_btn": "¡A JUGAR! 🚀",
        "ta_k_ready": "¡PREPARADOS!",
        "ta_k_turn": "Es el turno de:",
        "ta_k_start_turn": "EMPEZAR TURNO ▶️",
        "ta_k_loading": "CARGANDO...",
        "ta_k_correct": "¡ACERTADA! 🌟",
        "ta_k_pass": "PASAR / TABÚ ❌",
        "ta_k_round_pts": "Puntos ronda: ",
        "ta_k_tut_btn": "❓ Instrucciones",
        "ta_k_tut_title": "📖 ¿Cómo Jugar?",
        "ta_k_tut_step1_t": "Añade jugadores",
        "ta_k_tut_step1_d": "Escribe el nombre de los amigos o equipos que van a jugar.",
        "ta_k_tut_step2_t": "Describe la foto",
        "ta_k_tut_step2_d": "Cuando sea tu turno, explica la imagen que ves a tu equipo.",
        "ta_k_tut_step3_t": "¡Evita el Tabú!",
        "ta_k_tut_step3_d": "No digas la palabra principal ni las palabras prohibidas de la caja.",
        "ta_k_tut_step4_t": "Consigue puntos",
        "ta_k_tut_step4_d": "¡Adivina el máximo de fotos antes de que el tiempo se acabe!",
        "ta_k_tut_close": "¡ENTENDIDO! 🚀",
        "ta_k_mission_done": "¡MISIÓN CUMPLIDA! 🚀",
        "ta_k_winner_is": "¡El ganador es <b>{name}</b>!<br>{ranking}",
        "ta_k_pts": "puntos",
        "ta_k_new_game": "Nueva Partida"
    },
    en: {
        "ta_k_title": "TABOO KIDS",
        "ta_k_add_players": "Add players:",
        "ta_k_name_plc": "Name...",
        "ta_k_min_players": "MIN 2 PLAYERS",
        "ta_k_play_btn": "PLAY! 🚀",
        "ta_k_ready": "READY!",
        "ta_k_turn": "It's the turn of:",
        "ta_k_start_turn": "START TURN ▶️",
        "ta_k_loading": "LOADING...",
        "ta_k_correct": "CORRECT! 🌟",
        "ta_k_pass": "PASS / TABOO ❌",
        "ta_k_round_pts": "Round points: ",
        "ta_k_tut_btn": "❓ Instructions",
        "ta_k_tut_title": "📖 How to Play?",
        "ta_k_tut_step1_t": "Add players",
        "ta_k_tut_step1_d": "Write the name of the friends or teams playing.",
        "ta_k_tut_step2_t": "Describe the photo",
        "ta_k_tut_step2_d": "When it's your turn, explain the picture you see to your team.",
        "ta_k_tut_step3_t": "Avoid the Taboo!",
        "ta_k_tut_step3_d": "Don't say the main word or the forbidden words in the box.",
        "ta_k_tut_step4_t": "Earn points",
        "ta_k_tut_step4_d": "Guess as many photos as possible before time runs out!",
        "ta_k_tut_close": "GOT IT! 🚀",
        "ta_k_mission_done": "MISSION ACCOMPLISHED! 🚀",
        "ta_k_winner_is": "The winner is <b>{name}</b>!<br>{ranking}",
        "ta_k_pts": "points",
        "ta_k_new_game": "New Game"
    }
};
