const translations = {
    es: {
        "tk_tut_btn": "❓ Instrucciones",
        "tk_title": "TRIVIAL KIDS",
        "tk_how_many": "¿Cuántos jugadores sois?",
        "tk_1p": "1 Jugador 🧒",
        "tk_2p": "2 Jugadores 🧒👧",
        "tk_3p": "3 Jugadores 🧒👧👦",
        "tk_4p": "4 Jugadores 🧒👧👦👧",
        "tk_play_btn": "▶️ ¡A JUGAR!",
        "tk_loading": "Cargando...",
        "tk_next_btn": "SIGUIENTE ➡️",
        "tk_tut_title": "📖 ¿Cómo Jugar?",
        "tk_tut_step1_t": "¡Reúne a tus amigos!",
        "tk_tut_step1_d": "Elige cuántos vais a jugar y escribe vuestros nombres mágicos.",
        "tk_tut_step2_t": "Atento al turno",
        "tk_tut_step2_d": "Mira arriba para saber a quién le toca responder. ¡Fíjate bien!",
        "tk_tut_step3_t": "¡Cuidado con el tiempo!",
        "tk_tut_step3_d": "Tienes 20 segundos para elegir la respuesta correcta. ¡No te despistes!",
        "tk_tut_step4_t": "Gana Estrellas",
        "tk_tut_step4_d": "Acierta preguntas para ganar estrellas ⭐. ¡Quien tenga más gana!",
        "tk_tut_close": "¡ENTENDIDO! 🚀",
        "tk_player_def": "Jugador",
        "tk_time_out_title": "¡Oh no! ⏰",
        "tk_time_out_text": "Se acabó el tiempo.",
        "tk_stars": "Estrellas: {pts} ⭐",
        "tk_correct_title": "¡GENIAL! 🌟",
        "tk_wrong_title": "¡Ups! 😅",
        "tk_tie_title": "¡Empate Mágico! 🤝✨",
        "tk_tie_text": "¡Ha habido un empate entre <b>{names}</b>!",
        "tk_win_title": "¡Fin del juego! 🎉",
        "tk_win_text": "¡El ganador es <b>{name}</b>!",
        "tk_stars_word": "estrellas",
        "tk_play_again": "¡Jugar otra vez!",
        "tk_preguntas": [
            { texto: "¿Cómo se llama la reina del hielo en Frozen? ❄️", respuestas: [{ texto: "Anna", correct: false }, { texto: "Elsa", correct: true }, { texto: "Olaf", correct: false }, { texto: "Moana", correct: false }] },
            { texto: "¿Qué comen los pandas gigantes? 🐼", respuestas: [{ texto: "Pizza", correct: false }, { texto: "Bambú", correct: true }, { texto: "Pescado", correct: false }, { texto: "Helado", correct: false }] },
            { texto: "¿Cuál es el color de Bob Esponja? 🧽", respuestas: [{ texto: "Rosa", correct: false }, { texto: "Verde", correct: false }, { texto: "Amarillo", correct: true }, { texto: "Azul", correct: false }] },
            { texto: "¿Qué animal es el mejor amigo del hombre? 🐶", respuestas: [{ texto: "El gato", correct: false }, { texto: "El perro", correct: true }, { texto: "El loro", correct: false }, { texto: "El hámster", correct: false }] },
            { texto: "¿Cuántas patas tiene una araña? 🕷️", respuestas: [{ texto: "6", correct: false }, { texto: "4", correct: false }, { texto: "8", correct: true }, { texto: "10", correct: false }] },
            { texto: "¿Quién es el enemigo de Batman? 🦇", respuestas: [{ texto: "El Joker", correct: true }, { texto: "Thanos", correct: false }, { texto: "Voldemort", correct: false }, { texto: "Bob Esponja", correct: false }] },
            { texto: "¿Qué fruta es amarilla y alargada? 🍌", respuestas: [{ texto: "Manzana", correct: false }, { texto: "Uva", correct: false }, { texto: "Plátano", correct: true }, { texto: "Naranja", correct: false }] },
            { texto: "¿Dónde vive Nemo? 🐠", respuestas: [{ texto: "En la selva", correct: false }, { texto: "En el mar", correct: true }, { texto: "En el espacio", correct: false }, { texto: "En una cueva", correct: false }] },
            { texto: "¿Qué sonido hace la vaca? 🐄", respuestas: [{ texto: "Muuu", correct: true }, { texto: "Guau", correct: false }, { texto: "Miau", correct: false }, { texto: "Beee", correct: false }] },
            { texto: "¿Si mezclas rojo y amarillo, qué color sale? 🎨", respuestas: [{ texto: "Verde", correct: false }, { texto: "Morado", correct: false }, { texto: "Naranja", correct: true }, { texto: "Negro", correct: false }] }
        ]
    },
    en: {
        "tk_tut_btn": "❓ Instructions",
        "tk_title": "TRIVIAL KIDS",
        "tk_how_many": "How many players?",
        "tk_1p": "1 Player 🧒",
        "tk_2p": "2 Players 🧒👧",
        "tk_3p": "3 Players 🧒👧👦",
        "tk_4p": "4 Players 🧒👧👦👧",
        "tk_play_btn": "▶️ PLAY!",
        "tk_loading": "Loading...",
        "tk_next_btn": "NEXT ➡️",
        "tk_tut_title": "📖 How to Play?",
        "tk_tut_step1_t": "Gather your friends!",
        "tk_tut_step1_d": "Choose how many will play and write your magical names.",
        "tk_tut_step2_t": "Watch your turn",
        "tk_tut_step2_d": "Look up to see whose turn it is to answer. Pay attention!",
        "tk_tut_step3_t": "Watch the time!",
        "tk_tut_step3_d": "You have 20 seconds to choose the correct answer. Don't get distracted!",
        "tk_tut_step4_t": "Earn Stars",
        "tk_tut_step4_d": "Answer correctly to earn stars ⭐. Whoever gets the most wins!",
        "tk_tut_close": "GOT IT! 🚀",
        "tk_player_def": "Player",
        "tk_time_out_title": "Oh no! ⏰",
        "tk_time_out_text": "Time's up.",
        "tk_stars": "Stars: {pts} ⭐",
        "tk_correct_title": "AWESOME! 🌟",
        "tk_wrong_title": "Oops! 😅",
        "tk_tie_title": "Magical Tie! 🤝✨",
        "tk_tie_text": "There's a tie between <b>{names}</b>!",
        "tk_win_title": "Game Over! 🎉",
        "tk_win_text": "The winner is <b>{name}</b>!",
        "tk_stars_word": "stars",
        "tk_play_again": "Play again!",
        "tk_preguntas": [
            { texto: "What is the name of the ice queen in Frozen? ❄️", respuestas: [{ texto: "Anna", correct: false }, { texto: "Elsa", correct: true }, { texto: "Olaf", correct: false }, { texto: "Moana", correct: false }] },
            { texto: "What do giant pandas eat? 🐼", respuestas: [{ texto: "Pizza", correct: false }, { texto: "Bamboo", correct: true }, { texto: "Fish", correct: false }, { texto: "Ice Cream", correct: false }] },
            { texto: "What color is SpongeBob? 🧽", respuestas: [{ texto: "Pink", correct: false }, { texto: "Green", correct: false }, { texto: "Yellow", correct: true }, { texto: "Blue", correct: false }] },
            { texto: "What animal is man's best friend? 🐶", respuestas: [{ texto: "Cat", correct: false }, { texto: "Dog", correct: true }, { texto: "Parrot", correct: false }, { texto: "Hamster", correct: false }] },
            { texto: "How many legs does a spider have? 🕷️", respuestas: [{ texto: "6", correct: false }, { texto: "4", correct: false }, { texto: "8", correct: true }, { texto: "10", correct: false }] },
            { texto: "Who is Batman's enemy? 🦇", respuestas: [{ texto: "The Joker", correct: true }, { texto: "Thanos", correct: false }, { texto: "Voldemort", correct: false }, { texto: "SpongeBob", correct: false }] },
            { texto: "What fruit is yellow and long? 🍌", respuestas: [{ texto: "Apple", correct: false }, { texto: "Grape", correct: false }, { texto: "Banana", correct: true }, { texto: "Orange", correct: false }] },
            { texto: "Where does Nemo live? 🐠", respuestas: [{ texto: "In the jungle", correct: false }, { texto: "In the sea", correct: true }, { texto: "In space", correct: false }, { texto: "In a cave", correct: false }] },
            { texto: "What sound does a cow make? 🐄", respuestas: [{ texto: "Moo", correct: true }, { texto: "Woof", correct: false }, { texto: "Meow", correct: false }, { texto: "Baa", correct: false }] },
            { texto: "If you mix red and yellow, what color do you get? 🎨", respuestas: [{ texto: "Green", correct: false }, { texto: "Purple", correct: false }, { texto: "Orange", correct: true }, { texto: "Black", correct: false }] }
        ]
    }
};
